version: '3.8'

services:
  ansible-packer-terraform:
    container_name: ansible-packer-terraform
    hostname: ansible-packer-terraform
    image: ansible-packer-terraform:latest
    build:
      context: "."
      args:
        AWSCLI_VERSION: "${AWSCLI_VERSION}"
        PASSWORD: "${ANSIBLE_PASSWORD}"
        USERUID: "${USERUID}"
        USERGID: "${USERGID}"
    privileged: false
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    mem_limit: 1g
    environment:
      - TIMEZONE=${TIMEZONE}
      - HOST_DOCKER_GID=/var/run/docker.sock
    ports:
      - "0.0.0.0:${SSH_PORT}:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ../:/home/ansible/ansible-code
      - ./authorized_keys:/home/ansible/.ssh/authorized_keys

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.100.0.0/24
